from __future__ import annotations

DATA_METHODS: dict[str, str] = {
    "revenue_total": "spKDO_Aggregate group_by=total",
    "revenue_by_week": "spKDO_Aggregate group_by=week",
    "revenue_by_month": "spKDO_Aggregate group_by=month",
    "revenue_by_master": "spKDO_Aggregate group_by=master",
    "revenue_by_service": "spKDO_Aggregate group_by=service",
    "revenue_by_salon": "spKDO_Aggregate group_by=salon",
    "revenue_by_channel": "spKDO_Aggregate group_by=channel",
    "clients_outflow": "spKDO_ClientList filter=outflow",
    "clients_leaving": "spKDO_ClientList filter=leaving",
    "clients_forecast": "spKDO_ClientList filter=forecast",
    "clients_noshow": "spKDO_ClientList filter=noshow",
    "clients_quality": "spKDO_ClientList filter=quality",
    "clients_birthday": "spKDO_ClientList filter=birthday",
    "clients_all": "spKDO_ClientList filter=all",
    "comm_all_by_reason": "spKDO_CommAgg reason=all group_by=reason",
    "comm_all_by_result": "spKDO_CommAgg reason=all group_by=result",
    "comm_all_by_manager": "spKDO_CommAgg reason=all group_by=manager",
    "comm_all_list": "spKDO_CommAgg reason=all group_by=list",
    "comm_outflow_by_reason": "spKDO_CommAgg reason=outflow group_by=reason",
    "comm_leaving_by_result": "spKDO_CommAgg reason=leaving group_by=result",
    "comm_forecast_by_result": "spKDO_CommAgg reason=forecast group_by=result",
    "comm_noshow_by_manager": "spKDO_CommAgg reason=noshow group_by=manager",
    "comm_quality_by_result": "spKDO_CommAgg reason=quality group_by=result",
    "comm_birthday_by_result": "spKDO_CommAgg reason=birthday group_by=result",
    "comm_waitlist_by_manager": "spKDO_CommAgg reason=waitlist group_by=manager",
    "comm_opz_by_result": "spKDO_CommAgg reason=opz group_by=result",
}
